BULK_STATE_OPEN = 'Open'
BULK_STATE_UPLOAD_COMPLETE = 'UploadComplete'
BULK_STATE_ABORTED = 'Aborted'
BULK_STATE_JOB_COMPLETE = 'JobComplete'
BULK_STATE_FAILED = 'Failed'
BULK_STATES_DONE = [BULK_STATE_JOB_COMPLETE, BULK_STATE_ABORTED, BULK_STATE_FAILED]
BULK_STATES_FAIL = [BULK_STATE_ABORTED, BULK_STATE_FAILED]