STATUS_SUCCEEDED = 'Succeeded'
STATUS_FAILED = 'Failed'
STATUS_QUEUED = 'Queued'
STATUS_PENDING = 'Pending'
STATUS_INPROGRESS = 'InProgress'
STATUS_CANCELED = 'Canceled'
STATUSES_PENDING = [
    STATUS_QUEUED,
    STATUS_PENDING,
    STATUS_INPROGRESS
]
STATUSES_DONE = [
    STATUS_SUCCEEDED,
    STATUS_FAILED,
    STATUS_CANCELED
]