TEST_LEVEL_NO_TEST_RUN = 'NoTestRun'
TEST_LEVEL_RUN_SPECIFIED_TESTS = 'RunSpecifiedTests'
TEST_LEVEL_RUN_LOCAL_TESTS = 'RunLocalTests'
TEST_LEVEL_RUN_ALL_TESTS_IN_ORG = 'RunAllTestsInOrg'
TEST_LEVELS = [
    TEST_LEVEL_NO_TEST_RUN,
    TEST_LEVEL_RUN_SPECIFIED_TESTS,
    TEST_LEVEL_RUN_LOCAL_TESTS,
    TEST_LEVEL_RUN_ALL_TESTS_IN_ORG
]